---
# See https://github.com/jvautier/project-cli
fullname: jvautier/ansible-role-chef-workstation
description: Install chef workstation through ansible
tags:
  - ansible
  - ansible-role
  - chef-workstation
github:
  has_issues: true
  has_projects: false
  has_wiki: false
